/**
 * @module    state
 * @summary   Fassade — re-exportiert alle State-Operationen aus state-core.js, StorageManager.js, PCManager.js, EncounterManager.js. IMPORTIERE DIESE DATEI, NICHT state-core.js direkt.
 * @exports   getState, getActivePC, updatePCField, updatePCBatch, addPCWeapon, updatePCWeapon, addPCFeat, addPCArmor, addPCItem, updatePCItemEffect, applyDamage, nextTurn, loadSampleData u.v.m.
 * @reads     Zustand wird vollständig via getState()/getActivePC() abgefragt
 * @stateOps  Alle Mutationen via PCManager.js und EncounterManager.js — nie state-core.js direkt nutzen
 * @depends   state/state-core.js, state/StorageManager.js, state/PCManager.js, state/EncounterManager.js
 * @notHere   Mutation-Implementierungen → state/PCManager.js | Encounter-Aktionen → state/EncounterManager.js | Core-Events → state/state-core.js
 */
// Facade pattern for state management in v3.0
// Re-exports all functions from sub-managers to maintain 100% backwards compatibility.

import {
  getState,
  registerStateChangedCallback,
  registerPCChangedCallback,
  registerSessionChangedCallback,
  setRole,
  getRole,
  getActivePC,
  updateSession
} from './state/state-core.js';

import {
  saveToStorage,
  loadFromStorage,
  clearState
} from './state/StorageManager.js';

import {
  recalculatePCStats,
  recalculateDailyAbilities,
  updatePCBatch,
  addPCClass,
  removePCClass,
  updatePCClassLevel,
  updatePCClassType,
  clearPCClasses,
  togglePCACF,
  clearActivePC,
  updatePCField,
  updatePCNumber,
  updatePCWeapon,
  addPCWeapon,
  deletePCWeapon,
  updatePCSpellSlotsMax,
  updatePCSpellSlotsUsed,
  addPCDailyAbility,
  removePCDailyAbility,
  updatePCDailyAbilityUsed,
  resetDailyResources,
  syncPCToHost,
  addPCFeat,
  removePCFeat,
  addPCSkillTrick,
  removePCSkillTrick,
  togglePCDefensiveFighting,
  togglePCTotalDefense,
  savePCSpellTemplate,
  deletePCSpellTemplate,
  applyPCSpellTemplate,
  clearPreparedSpells,
  addPCArmor,
  removePCArmor,
  togglePCArmorEquip,
  updatePCArmorField,
  setPCAutoAC,
  togglePCWeaponEquip,
  addPCItem,
  deletePCItem,
  reorderPCItems,
  updatePCItem,
  togglePCItemEquip,
  addPCItemEffect,
  deletePCItemEffect,
  updatePCItemEffect,
  equipPCItem,
  unequipPCItem,
  swapPCItem,
  usePCItemCharge,
  usePCItemAction,
  addPCItemFromCompendium,
  consumeSmiteEvilCharge,
  togglePCRage
} from './state/PCManager.js';

import {
  updateMeta,
  addCombatant,
  removeCombatant,
  sortCombatants,
  updateCombatantField,
  updateCombatantNumber,
  applyDamage,
  applyTempHP,
  toggleCondition,
  setConditionDuration,
  addConcentration,
  removeConcentration,
  updateConcentrationField,
  nextTurn,
  prevTurn,
  nextRound,
  resetCombat,
  importEncounterState,
  mergeIncomingPC,
  loadSampleData
} from './state/EncounterManager.js';

// Named exports
export {
  getState,
  registerStateChangedCallback,
  registerPCChangedCallback,
  registerSessionChangedCallback,
  setRole,
  getRole,
  getActivePC,
  updateSession,
  
  saveToStorage,
  loadFromStorage,
  clearState,
  
  recalculatePCStats,
  recalculateDailyAbilities,
  updatePCBatch,
  addPCClass,
  removePCClass,
  updatePCClassLevel,
  updatePCClassType,
  clearPCClasses,
  clearActivePC,
  updatePCField,
  updatePCNumber,
  updatePCWeapon,
  addPCWeapon,
  deletePCWeapon,
  updatePCSpellSlotsMax,
  updatePCSpellSlotsUsed,
  addPCDailyAbility,
  removePCDailyAbility,
  updatePCDailyAbilityUsed,
  resetDailyResources,
  syncPCToHost,
  addPCFeat,
  removePCFeat,
  addPCSkillTrick,
  removePCSkillTrick,
  togglePCDefensiveFighting,
  togglePCTotalDefense,
  savePCSpellTemplate,
  deletePCSpellTemplate,
  applyPCSpellTemplate,
  clearPreparedSpells,
  addPCArmor,
  removePCArmor,
  togglePCArmorEquip,
  updatePCArmorField,
  setPCAutoAC,
  togglePCWeaponEquip,
  addPCItem,
  deletePCItem,
  reorderPCItems,
  updatePCItem,
  togglePCItemEquip,
  addPCItemEffect,
  deletePCItemEffect,
  updatePCItemEffect,
  equipPCItem,
  unequipPCItem,
  swapPCItem,
  usePCItemCharge,
  usePCItemAction,
  addPCItemFromCompendium,
  
  updateMeta,
  addCombatant,
  removeCombatant,
  sortCombatants,
  updateCombatantField,
  updateCombatantNumber,
  applyDamage,
  applyTempHP,
  toggleCondition,
  setConditionDuration,
  addConcentration,
  removeConcentration,
  updateConcentrationField,
  nextTurn,
  prevTurn,
  nextRound,
  resetCombat,
  importEncounterState,
  mergeIncomingPC,
  loadSampleData
};

// Object export facade
export const CombatState = {
  updateSession,
  getState,
  saveToStorage,
  loadFromStorage,
  clearState,
  setRole,
  getRole,
  getActivePC,
  recalculatePCStats,
  recalculateDailyAbilities,
  updatePCBatch,
  addPCClass,
  removePCClass,
  updatePCClassLevel,
  updatePCClassType,
  clearPCClasses,
  togglePCACF,
  clearActivePC,
  updatePCField,
  updatePCNumber,
  updatePCWeapon,
  addPCWeapon,
  deletePCWeapon,
  updatePCSpellSlotsMax,
  updatePCSpellSlotsUsed,
  addPCDailyAbility,
  removePCDailyAbility,
  updatePCDailyAbilityUsed,
  resetDailyResources,
  syncPCToHost,
  addPCFeat,
  removePCFeat,
  addPCSkillTrick,
  removePCSkillTrick,
  togglePCDefensiveFighting,
  togglePCTotalDefense,
  savePCSpellTemplate,
  deletePCSpellTemplate,
  applyPCSpellTemplate,
  clearPreparedSpells,
  addPCArmor,
  removePCArmor,
  togglePCArmorEquip,
  updatePCArmorField,
  setPCAutoAC,
  togglePCWeaponEquip,
  addPCItem,
  deletePCItem,
  reorderPCItems,
  updatePCItem,
  togglePCItemEquip,
  addPCItemEffect,
  deletePCItemEffect,
  updatePCItemEffect,
  equipPCItem,
  unequipPCItem,
  swapPCItem,
  usePCItemCharge,
  usePCItemAction,
  addPCItemFromCompendium,
  consumeSmiteEvilCharge,
  togglePCRage,
  updateMeta,
  addCombatant,
  removeCombatant,
  sortCombatants,
  updateCombatantField,
  updateCombatantNumber,
  applyDamage,
  applyTempHP,
  toggleCondition,
  setConditionDuration,
  addConcentration,
  removeConcentration,
  updateConcentrationField,
  nextTurn,
  prevTurn,
  nextRound,
  resetCombat,
  importEncounterState,
  mergeIncomingPC,
  loadSampleData,
  registerStateChangedCallback,
  registerPCChangedCallback,
  registerSessionChangedCallback
};
